import {
  IconArrowRight,
  IconArrowLeft,
  IconArrowUpRight,
  IconBrandFacebook,
  IconBrandInstagram,
  IconBrandWhatsapp,
  IconCalendarCheck,
  IconClipboardCheck,
  IconCheck,
  IconCookie,
  IconDiamond,
  IconDental,
  IconFileText,
  IconHeadset,
  IconHeart,
  IconInfoCircle,
  IconLeaf,
  IconLock,
  IconMail,
  IconMap2,
  IconMapPin,
  IconMenu2,
  IconMessageCircle,
  IconMinus,
  IconPhone,
  IconPlus,
  IconQuote,
  IconRoute,
  IconShieldCheck,
  IconStar,
  IconTarget,
  IconUser,
  IconUsers,
  IconWriting,
  IconX,
  type IconProps,
} from "@tabler/icons-react";

const ICONS = {
  "arrow-right": IconArrowRight,
  "arrow-left": IconArrowLeft,
  "arrow-up-right": IconArrowUpRight,
  calendar: IconCalendarCheck,
  clipboard: IconClipboardCheck,
  chat: IconBrandWhatsapp,
  check: IconCheck,
  close: IconX,
  cookie: IconCookie,
  diamond: IconDiamond,
  dental: IconDental,
  document: IconFileText,
  facebook: IconBrandFacebook,
  headset: IconHeadset,
  heart: IconHeart,
  info: IconInfoCircle,
  instagram: IconBrandInstagram,
  leaf: IconLeaf,
  lock: IconLock,
  mail: IconMail,
  map: IconMap2,
  "map-pin": IconMapPin,
  menu: IconMenu2,
  message: IconMessageCircle,
  minus: IconMinus,
  phone: IconPhone,
  plus: IconPlus,
  quote: IconQuote,
  route: IconRoute,
  shield: IconShieldCheck,
  star: IconStar,
  target: IconTarget,
  user: IconUser,
  users: IconUsers,
  whatsapp: IconBrandWhatsapp,
  writing: IconWriting,
} as const;

export type IconName = keyof typeof ICONS;
type Props = Omit<IconProps, "ref"> & { name: IconName };

export default function Icon({ name, size = 22, stroke = 1.8, ...props }: Props) {
  const IconComponent = ICONS[name];
  return <IconComponent aria-hidden="true" focusable="false" size={size} stroke={stroke} {...props} />;
}
